# Generated by Django 3.2.9 on 2021-11-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50)),
                ('serive_definition', models.TextField()),
                ('farmer_id', models.ManyToManyField(related_name='service', to='modules.Farmer')),
            ],
        ),
    ]
