# Generated by Django 3.2.9 on 2021-11-13 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_event_experts_new_seminar_tips'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOfGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_good', models.CharField(max_length=50)),
                ('how_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('where_to_deliver', models.CharField(max_length=50)),
                ('status', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('deadline_to_delivery', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_fertilizer', models.CharField(max_length=20)),
                ('used_for_what', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('how_much_available', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LocalGlobalMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_good', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('how_much_available', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MachineOwners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('TypeOfMachine', models.CharField(max_length=50)),
                ('Cost_Machine_day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeOfMachine', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=30)),
                ('who_rent', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
