# Generated by Django 3.2.9 on 2021-11-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_deliveryofgoods_fertilizer_localglobalmarket_machineowners_machines'),
    ]

    operations = [
        migrations.AddField(
            model_name='localglobalmarket',
            name='local_global',
            field=models.BooleanField(default=False),
        ),
    ]
