# Generated by Django 3.2.9 on 2021-11-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_localglobalmarket_local_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='localglobalmarket',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
